name: book_shelf
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-277.0.dev <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  carousel_slider: ^4.2.1
  glassmorphism: ^3.0.0
  http: ^0.13.5
  convex_bottom_bar: ^3.2.0
  easy_refresh: ^3.3.1  
  provider: ^6.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - lib/images/book.jpg
    - lib/images/pop_books/Pop001.jpg
    - lib/images/pop_books/Pop002.jpg
    - lib/images/pop_books/Pop003.jpg
    - lib/images/pop_books/Pop004.jpg
    - lib/images/pop_books/Pop005.jpg
    - lib/images/pop_books/Pop006.jpg
    - lib/images/pop_books/Pop007.jpg
    - lib/images/pop_books/Pop008.jpg
    - lib/images/pop_books/Pop009.jpg
    - lib/images/pop_books/Pop010.jpg
    - lib/images/pop_books/Pop011.jpg
    - lib/images/pop_books/Pop012.jpg
    - lib/images/tech_books/C001.JPG
    - lib/images/tech_books/Ceph001.jpg
    - lib/images/tech_books/Compile001.jpg
    - lib/images/tech_books/Compile002.jpg
    - lib/images/tech_books/Compile003.jpg
    - lib/images/tech_books/Computer001.jpg
    - lib/images/tech_books/Computer002.jpg
    - lib/images/tech_books/CSS001.JPG
    - lib/images/tech_books/DataStructure001.jpg
    - lib/images/tech_books/DataStructure002.jpg
    - lib/images/tech_books/DB001.JPG
    - lib/images/tech_books/DB002.JPG
    - lib/images/tech_books/DB003.JPG
    - lib/images/tech_books/DB004.JPG
    - lib/images/tech_books/Game001.jpg
    - lib/images/tech_books/Go001.jpg
    - lib/images/tech_books/Go002.jpg
    - lib/images/tech_books/Go003.jpg
    - lib/images/tech_books/Go004.jpg
    - lib/images/tech_books/Go005.jpg
    - lib/images/tech_books/HTML001.JPG
    - lib/images/tech_books/Java001.jpg
    - lib/images/tech_books/Java002.jpg
    - lib/images/tech_books/Java003.jpg
    - lib/images/tech_books/Java004.jpg
    - lib/images/tech_books/Java005.jpg
    - lib/images/tech_books/Java006.jpg
    - lib/images/tech_books/Java007.jpg
    - lib/images/tech_books/JS001.JPG
    - lib/images/tech_books/js002.jpg
    - lib/images/tech_books/js003.jpg
    - lib/images/tech_books/js004.jpg
    - lib/images/tech_books/Linux001.jpg
    - lib/images/tech_books/Linux002.jpg
    - lib/images/tech_books/Linux003.jpg
    - lib/images/tech_books/Linux004.jpg
    - lib/images/tech_books/Linux005.jpg
    - lib/images/tech_books/Linux006.jpg
    - lib/images/tech_books/Linux007.jpg
    - lib/images/tech_books/MicroService001.jpg
    - lib/images/tech_books/MicroService002.jpg
    - lib/images/tech_books/Network001.jpg
    - lib/images/tech_books/Network002.jpg
    - lib/images/tech_books/Programming001.jpg
    - lib/images/tech_books/Programming002.jpg
    - lib/images/tech_books/Python001.jpg
    - lib/images/tech_books/Python002.jpg
    - lib/images/tech_books/Python003.jpg
    - lib/images/tech_books/Python004.jpg
    - lib/images/tech_books/Python005.jpg
    - lib/images/tech_books/Python006.jpg
    - lib/images/tech_books/Python007.jpg
    - lib/images/tech_books/Python008.jpg
    - lib/images/tech_books/Python009.jpg
    - lib/images/tech_books/Python010.jpg
    - lib/images/tech_books/Python011.jpg
    - lib/images/tech_books/Python012.jpg
    - lib/images/tech_books/Python013.jpg
    - lib/images/tech_books/Python014.jpg
    - lib/images/tech_books/Redis001.jpg
    - lib/images/tech_books/Redis002.jpg
    - lib/images/tech_books/System001.jpg
    - lib/images/tech_books/Virtualization001.jpg
    - lib/images/tech_books/Virtualization002.jpg
    - lib/images/tech_books/Virtualization003.jpg
    - lib/images/tech_books/Virtualization004.jpg
    - lib/images/tech_books/Virtualization005.jpg
    - lib/images/tech_books/Web001.jpg
    - lib/images/tech_books/Web002.jpg
    - lib/images/tech_books/Web003.jpg
    - lib/images/tech_books/Web004.jpg
    - lib/images/tech_books/Web005.jpg
    - lib/images/tech_books/Web006.jpg
    - lib/images/tech_books/Web007.jpg
    - lib/images/celebrity/Bill Gates.webp
    - lib/images/celebrity/Book Shelf.jpg
    - lib/images/celebrity/Jeff Bezos.webp
    - lib/images/celebrity/Larry Ellison.webp
    - lib/images/celebrity/Mark Zuckerberg.webp
    - lib/images/celebrity/Michael Bloomberg.webp
    - lib/images/celebrity/Muhtar Kent.webp
    - lib/images/celebrity/Oprah Winfrey.webp
    - lib/images/celebrity/Richard Branson.webp
    - lib/images/celebrity/Tim Cook.webp
    - lib/images/celebrity/Warren Buffett.webp
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
